# Generated by Django 3.2.6 on 2021-10-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzlom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='login1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='parol',
            new_name='parol2',
        ),
    ]
