# Generated by Django 3.2.6 on 2021-10-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzlom', '0002_auto_20211017_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userbek',
        ),
    ]
